### PR TITLE
Added new resource

### PR DESCRIPTION
**Pull request by EvoluoGames**

### CODE REVIEW

**Comment by delapuente** [comment]
What do you think, @belen-albeza ?

**Review by belen-albeza — CHANGES_REQUESTED** [review]
I'm OK with the Game Mechanic Explorer (thanks!), but I'm reluctant to include more than one app that do the same thing. I have still not tried JPixel, so I'd stick with Pyxel Edit for now.

**Comment by EvoluoGames** [comment]
@belen-albeza I removed the JPixel resource.

**Comment by delapuente** [comment]
We are good, then.

**Pull request merged**
